version: '3.4'

services:
  quizmania:
    image: quizmania
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      HTTP_PORT: 8080
      API_ACCESS_TOKENS: TEST_API_KEY,TEST_API_KEY2
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
    networks:
      - backend 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - backend 

networks:
  backend:
    driver: bridge

volumes:
  data: